name: Run tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install GraphViz
        uses: tlylt/install-graphviz@v1

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r requirements.txt
          python -m pip list

      - name: Build parser
        run: |
          ./scripts/build_parser.py

      - name: Run tests
        run: |
          ./scripts/run_tests.py

      - name: Check DOT working
        run: |
          ./scripts/run_parser.py < ./examples/from_readme.fl
